---
- hosts: 172.31.95.94
  become: yes 
  tasks: 
  - name: i want install git
    apt:
     name: git
     state: present 
    
    

  - name: i want install wget
    apt:
     name: wget
     stateeeee: present 
    ignore_errors: yes 
    
     
  - name: i want install tree
    apt:
     name: tree 
     state: present 
    
     
