---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install java in ubuntu
     apt:
       name: "{{myjavapakageforubuntu}}"
       state: present
     when: ansible_os_family =="Debian"

   - name: i want to install in redhat
     yum:
       name: "{{myjavapakageforredhat}}"
       state: present
     when: ansible_os_family =="RedHat"
     