---
- hosts: webservers
  become: yes
  tasks:
   - name: install java on ubuntu
     apt:
       name: "{{myjavapakageforubuntu}}"
       state: present 
     when: ansible_os_family == "Debian"

   - name: install java on redhat
     yum:
       name: "{{myjavapakageforredhat}}"
       state: present 
     when: ansible_os_family == "RedHat"