---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to install java in ansible node
    apt:
      name: "{{myjavapakageforubuntu}}"
      state: present 
    when: ansible_os_family == "Debian"

  - name: i want to install web server Redhat ansible node
    yum:
      name: "{{myjavapakageforubuntu}}"
      state: present 
    when: ansible_os_family == "RedHat"