---
- hosts: all
  become: yes
  tasks: 
  - name: install java on ubuntu nodes
    apt:
      name: "{{myjavapakageforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: install java on redhat nodes
    yum:
      name: "{{myjavapakageforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"