---
- hosts: webservers
  become: yes
  tasks: 
  - name: i want to install web server on ansible node
    apt:
      name: {{"mypakageforubuntu"}}
      state: present 
    when: ansible_os_family == "Debian"

  - name: i want to start my webserver
    service:
      name: {{"mypakageforubuntu"}}
      state: started
    when: ansible_os_family == "Debian"

  - name: i want to install web server Redhat ansible node
    yum:
      name: {{"mypakageforredhat"}}
      state: present 
    when: ansible_os_family == "RedHat"
     
  - name: i want to start my webserver
    service:
      name: {{"mypakageforredhat"}}
      state: started
    when: ansible_os_family == "RedHat"