---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to install web server on ansbile node
    apt:
      name: "{{mywebpakageforubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start my webserver 
    service:
      name: "{{mywebpakageforubuntu}}"
      state: started
    when: ansible_os_family =="Debian"


  - name: i want to install webserver RedHat ansible nodes
    yum:
      name: "{{mywebpakageforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start my webserver on RedHat ansbile nodes
    service:
       name: "{{mywebpakageforredhat}}"
       state: started
    when: ansible_os_family =="RedHat"